Traceback (most recent call last):
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Xinli\anaconda3\envs\ml22\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bag_clf = BaggingClassifier(DecisionTreeClassifer(),
                            n_estimators=500,
                            max_samples=100,
                            bootstrap=True)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mensemble[39;00m [38;5;28;01mimport[39;00m BaggingClassifier
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtree[39;00m [38;5;28;01mimport[39;00m DecisionTreeClassifier
[1;32m----> 4[0m bag_clf [38;5;241m=[39m BaggingClassifier([43mDecisionTreeClassifer[49m(),
[0;32m      5[0m                             n_estimators[38;5;241m=[39m[38;5;241m500[39m,
[0;32m      6[0m                             max_samples[38;5;241m=[39m[38;5;241m100[39m,
[0;32m      7[0m                             bootstrap[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

[1;31mNameError[0m: name 'DecisionTreeClassifer' is not defined
NameError: name 'DecisionTreeClassifer' is not defined

